---
title: "ISA 2026 Abstract"
format: docx
---

**Title**: "Leaders Unleashed: The Importance of Constraints on Hawkish Leaders"

**Abstract:** Over the past decade, data advances in the field of international relations have made it increasingly easy to systematically examine the role of political leaders in international conflict. These studies either consider which among a wide range of leader psychological, political, or background characteristics predict hawkishness, or else seek to construct indexes out of these characteristics that predict hawkishness. This study builds on this literature by considering the institutional context in which leaders exercise power. The argument is made that the strength of domestic constraints placed on leaders conditions whether their hawkishness translates into conflict initiation. Analysis using a recently developed measure of leader willingness to use force interacted with measures of executive constraints supports this argument. This study has implications for understanding the role of leaders in international relations by showing under which conditions leaders who are willing to use force actually do.

**Key words**: Conflict, Leaders, Hawkishness, Checks and Balances