---
title: "Analysis code"
format: html
---

## Setup

```{r}
library(tidyverse)
library(mgcv)
library(ggregtab)
library(sjPlot)
library(here)
library(coolorrr)
library(socsci)
source(
  here("_helpers", "_helpers_script.R")
)
set_palette(
  diverging = c("navy", "gray", "red")
)

saveit <- function(num, ht = 4, wt = 6) {
  ggsave(
    here::here(
      "_analysis",
      paste0("fig", num, ".png")
    ),
    height = ht,
    width = wt,
    dpi = 500
  )
}

my_theme <- function() {
  theme_bw() +
    theme(
      axis.title.x = element_text(size = 12),
      axis.title.y = element_text(size = 12),
      plot.title.position = "plot",
      plot.caption.position = "plot",
      plot.title = element_text(hjust = 0),
      plot.subtitle = element_text(hjust = 0),
      plot.caption = element_text(hjust = 0, size = 12)
    )
}

theme_set(my_theme())
```


## Data

```{r}
dt <- read_csv(
  here("_data", "_leader_year_data.csv")
)
```

## Regression analysis

The main outcome of interest is whether a leader initiates a MID against any other country. Using {mgcv} I'll estimate a generalized additive logit with leader willingness to use force (LWUF) interacted with polity using a nonlinear joint function.

```{r}
dt |>
  mutate(
    pdem = as.factor((polity2 > 5) + 0),
    pcon = as.factor((xconst > 1) + 0),
    vdem = as.factor((v2x_polyarchy > median(v2x_polyarchy, T)) + 0),
    vcon = as.factor((v2xnp_pres < median(v2xnp_pres, T)) + 0),
    pcat = frcode(
      pdem == 0 & pcon == 0 ~ "Unconstrained Non-Dem.",
      pdem == 0 & pcon == 1 ~ "Constrained Non-Dem.",
      pdem == 1 & pcon == 0 ~ "Unconstrained Dem.",
      pdem == 1 & pcon == 1 ~ "Constrained Dem."
    ),
    vcat = frcode(
      vdem == 0 & vcon == 0 ~ "Unconstrained Non-Dem.",
      vdem == 0 & vcon == 1 ~ "Constrained Non-Dem.",
      vdem == 1 & vcon == 0 ~ "Unconstrained Dem.",
      vdem == 1 & vcon == 1 ~ "Constrained Dem."
    )
  ) -> dt

## set-up an iterative process to estimate the models
logit_form <- miconset_init ~
  log(cinc) + log(1+land) + log(1+sea) + cowmaj +
  micspell + 
  I(micspell^2) +
  I(micspell^3) +
  s(ccode, bs = "re")
list(
  "Model 1" = update(
    logit_form, . ~ theta2_mean * pcon + pdem + .
  ),
  "Model 2" = update(
    logit_form, . ~ theta2_mean * pdem + pcon + .
  ),
  "Model 3" = update(
    logit_form, . ~ theta2_mean * pcat + .
  ),
  "Model 4" = update(
    logit_form, . ~ s(theta2_mean, by = pcon) + pcon + pdem + .
  ),
  "Model 5" = update(
    logit_form, . ~ s(theta2_mean, by = pdem) + pcon + pdem + .
  ),
  "Model 6" = update(
    logit_form, . ~ s(theta2_mean, by = pcat) + pcat + .
  ),
  "Model 7" = update(
    logit_form, . ~ theta2_mean * vcon + vdem + .
  ),
  "Model 8" = update(
    logit_form, . ~ theta2_mean * vdem + vcon + .
  ),
  "Model 9" = update(
    logit_form, . ~ theta2_mean * vcat + .
  ),
  "Model 10" = update(
    logit_form, . ~ s(theta2_mean, by = vcon) + vcon + vdem + .
  ),
  "Model 11" = update(
    logit_form, . ~ s(theta2_mean, by = vdem) + vcon + vdem + .
  ),
  "Model 12" = update(
    logit_form, . ~ s(theta2_mean, by = vcat) + vcat + .
  )
) |>
  map(
    ~ gam(
      .x,
      data = dt,
      family = binomial,
      method = "REML"
    )
  ) -> logit_models

list(
  "Model 1" = update(
    logit_form, . ~ te(theta2_mean, polity2, k = 5) + .
  ),
  "Model 2" = update(
    logit_form, . ~ te(theta2_mean, v2xlg_legcon, k = 5) + .
  ),
  "Model 3" = update(
    logit_form, . ~ te(theta2_mean, v2x_polyarchy, k = 5) + .
  )
) |>
  map(
    ~ gam(
      .x,
      data = dt,
      family = binomial,
      method = "REML"
    )
  ) -> logit_models
```

```{r}
logit_models |>
  map(summary)
```


```{r}
library(patchwork)
pm <- function(mod, int, x = NULL, clr = NULL, ttl = NULL) {
  plot_model(mod, "pred", terms = c("theta2_mean", int), ci.lvl = .834) +
  labs(title = ttl, x = x, y = NULL, color = clr, fill = clr)
}

p1 <- pm(logit_models[[1]], "polity2 [-5, 5]", "LWUF (M2)", "Polity 2", "(A)")
p2 <- pm(logit_models[[2]], "v2xlg_legcon [.25, .75]", "LWUF (M2)", "Leg. Constraints", "(B)")
p3 <- pm(logit_models[[3]], "v2x_polyarchy [.25, .75]", "LWUF (M2)", "Polyarchy", "(C)")
# p4 <- pm(logit_models[[4]], "v2xlg_legcon [.2, .8]", "LWUF (M2)")
# p5 <- pm(logit_models[[5]], "pdem", "LWUF (M2)")
# p6 <- pm(logit_models[[6]], "pcat", "LWUF (M2)")
# p7 <- pm(logit_models[[7]], "vcon", "LWUF (M2)")
# p8 <- pm(logit_models[[8]], "vdem", "LWUF (M2)")
# p9 <- pm(logit_models[[9]], "vcat", "LWUF (M2)")
# p10 <- pm(logit_models[[10]], "vcon", "LWUF (M2)")
# p11 <- pm(logit_models[[11]], "vdem", "LWUF (M2)")
# p12 <- pm(logit_models[[12]], "vcat", "LWUF (M2)")
```

```{r}
#| fig-height: 4
#| fig-width: 18
p1 + p2 + p3 +
  plot_annotation(
    title = "Probability of MIC initiation by leaders"
  )
saveit(1, 4, 18)
```

```{r}
#| fig-height: 4
#| fig-width: 18
draw(
  logit_models[[1]],
  se = F,
  shade = T,
  select = 1,
  scheme = 2
) +
  labs(
    title = "(A)",
    x = "LWUF (M2)",
    y = "Polity 2"
  ) -> h1
draw(
  logit_models[[2]],
  se = F,
  shade = T,
  select = 1,
  scheme = 2
) +
  labs(
    title = "(B)",
    x = "LWUF (M2)",
    y = "Leg. Constraints"
  ) -> h2
draw(
  logit_models[[3]],
  se = F,
  shade = T,
  select = 1,
  scheme = 2
) +
  labs(
    title = "(C)",
    x = "LWUF (M2)",
    y = "Polyarchy"
  ) -> h3
gridExtra::grid.arrange(h1, h2, h3, ncol = 3, nrow = 1)
saveit(2, 4, 18)
```


```{r}

summary(logit_models[[1]]) -> s
s$s.table |> 
  as_tibble() |>
  mutate(
    term = rownames(s$s.table)
  ) |>
  select(term, everything()) -> edf 
s$p.table |> 
  as_tibble() |>
  mutate(
    term = rownames(s$p.table)
  ) |>
  select(term, everything()) -> fix

colnames(edf) <- c("term", "estimate", "std.error", "statistic", "p.value")
colnames(fix) <- colnames(edf)
bind_rows(
  fix, edf
) |>
  mutate(
    conf.low = estimate - 1.96 * std.error,
    conf.high = estimate + 1.96 * std.error,
    model = "(1)",
    N = s$n
  ) -> s1

summary(logit_models[[2]]) -> s
s$s.table |> 
  as_tibble() |>
  mutate(
    term = rownames(s$s.table)
  ) |>
  select(term, everything()) -> edf 
s$p.table |> 
  as_tibble() |>
  mutate(
    term = rownames(s$p.table)
  ) |>
  select(term, everything()) -> fix

colnames(edf) <- c("term", "estimate", "std.error", "statistic", "p.value")
colnames(fix) <- colnames(edf)
bind_rows(
  fix, edf
) |>
  mutate(
    conf.low = estimate - 1.96 * std.error,
    conf.high = estimate + 1.96 * std.error,
    model = "(2)",
    N = s$n
  ) -> s2

summary(logit_models[[3]]) -> s
s$s.table |> 
  as_tibble() |>
  mutate(
    term = rownames(s$s.table)
  ) |>
  select(term, everything()) -> edf 
s$p.table |> 
  as_tibble() |>
  mutate(
    term = rownames(s$p.table)
  ) |>
  select(term, everything()) -> fix

colnames(edf) <- c("term", "estimate", "std.error", "statistic", "p.value")
colnames(fix) <- colnames(edf)
bind_rows(
  fix, edf
) |>
  mutate(
    conf.low = estimate - 1.96 * std.error,
    conf.high = estimate + 1.96 * std.error,
    model = "(3)",
    N = s$n
  ) -> s3

bind_rows(
  s1, s2, s3
) -> s
```

```{r}
#| fig-height: 8
#| fig-width: 6
ggregtab(
  s,
  ratio = 1/3,
  digits = 3
) +
  scale_y_discrete(
    limits = unique(s$term)[c(10, 12:11, 9:1)],
    labels = c(
      "Country RE",
      "te(M2, Polyarchy)",
      "te(M2, Leg. Con.)",
      "te(M2, Polity 2)",
      "Years^3",
      "Years^2",
      "Years",
      "Major Power",
      "Sea Contiguity (ln)",
      "Land Contiguity (ln)",
      "CINC",
      "(Intercept)"
    )
  ) +
  theme(
    axis.text.y = element_text(hjust = 0)
  )
saveit(3, 8, 6)
```



```{r}
library(socsci)
library(broom)
dt |>
  corr(polity2, v2xlg_legcon)
dt |>
  corr(polity2, v2x_polyarchy)
dt |>
  corr(v2xlg_legcon, v2x_polyarchy)
```


```{r}
dt |>
  drop_na(theta2_mean) |>
  summary()
```

```{r}
dt |>
  filter(theta2_mean < 0, polity2 %in% 4:5, miconset_init == 1) |>
  arrange(-events_init)
```

